# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

"""

!pip install opencv-python==4.7.0.72 retina-face tensorflow==2.12 keras==2.12 matplotlib

# RetinaFace Model
!wget https://github.com/deepinsight/insightface/releases/download/v0.1/retinaface-R50.zip
!unzip -o retinaface-R50.zip

# DEX Model (Caffe)
!wget https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/static/dex_imdb_wiki.caffemodel
!wget https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/static/age.prototxt

# Mini-Xception Model
!wget https://github.com/oarriaga/face_classification/raw/master/trained_models/emotion_models/fer2013_mini_XCEPTION.102-0.66.hdf5

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from retinaface import RetinaFace

# مدل سن (DEX)
age_net = cv2.dnn.readNetFromCaffe("age.prototxt", "dex_imdb_wiki.caffemodel")

# مدل احساسات (Mini-Xception)
emotion_model = load_model("fer2013_mini_XCEPTION.102-0.66.hdf5")
emotion_labels = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

def detect_faces(img):
    rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    faces = RetinaFace.detect_faces(rgb_img)
    face_boxes = []
    if isinstance(faces, dict):
        for face in faces.values():
            x, y, x2, y2 = face["facial_area"]
            face_boxes.append((x, y, x2 - x, y2 - y))
    return face_boxes

def predict_age(face_img):
    blob = cv2.dnn.blobFromImage(face_img, 1.0, (224, 224),
                                 (78.4263377603, 87.7689143744, 114.5902774601))
    age_net.setInput(blob)
    age_pred = age_net.forward()
    return int(age_pred[0].dot(np.arange(0, 101)).flatten())

def predict_emotion(face_img):
    face_gray = cv2.cvtColor(face_img, cv2.COLOR_BGR2GRAY)
    face_resized = cv2.resize(face_gray, (64, 64))
    face_processed = face_resized.reshape(1, 64, 64, 1).astype('float32') / 255.0
    emotion_pred = emotion_model.predict(face_processed)
    return emotion_labels[np.argmax(emotion_pred)]

from google.colab import files
uploaded = files.upload()

img = cv2.imread(list(uploaded.keys())[0])  # خواندن اولین تصویر آپلودشده
faces = detect_faces(img)

for (x, y, w, h) in faces:
    face_img = img[y:y+h, x:x+w]
    age = predict_age(face_img)
    emotion = predict_emotion(face_img)

    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
    cv2.putText(img, f"Age: {age}", (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
    cv2.putText(img, f"emotion: {emotion}", (x, y+h+20), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 0, 0), 2)

# نمایش
plt.figure(figsize=(8, 6))
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()